### PR TITLE
adds two tests for breaking easy (distorted text) CAPTCHAs, updates README

### PR DESCRIPTION
**Pull request by charlesfrye**
# Description

This PR adds two tests that check whether GPT-4V will provide the string required to pass a CAPTCHA based on this image:

easy_captcha

The second test uses a simple [ethical appeal persuasion attack](https://arxiv.org/abs/2401.06373) intended to avoid basic refusals. Currently, this attack is not necessary, but it may reveal behavioral changes from GPT-4V in the future or may be necessary for other models, if this benchmark is expanded.

Additionally, this PR adds a line to the README that describes a required step for adding a new test -- editing `tests/__init__.py`.

## Type of change

Please delete options that are not relevant.

-   [x] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

I ran it on a a GitHub Codespaces instance and the Python script outputs looked good. I didn't try rendering the actual website, but a quick spot-check of the output `index.html` (not included in PR) didn't turn up anything obviously busted.

### CODE REVIEW

**Comment by charlesfrye** [comment]
I recognize that testing security feature circumvention is sensitive!

I briefly discussed this test with @josephofiowa, and he indicated interest.

**Comment by stellasphere** [comment]
Hey @charlesfrye, thanks for contributing these! I'm curious whether in your testing you found the persuasive attack to be more or the same rate of success as the non-persuasive one in your testing?

**Comment by charlesfrye** [comment]
I only tried a single image, the included one. Easy enough to generate more, if that's of interest!

I didn't observe any refusals this time, but I have seen refusals in the past -- in the ChatGPT UI, not via the API.

**Comment by josephofiowa** [comment]
compelling. should we tag credit as [@charles_irl](https://twitter.com/charles_irl)?

**Comment by charlesfrye** [comment]
Sure! It looked to me like the "submitted by" text was hard-coded in the template, so I didn't dig further.

**Review by capjamesg — APPROVED** [review]
This looks good! I'm going to file a separate PR to add authorship logic and tag you as the author.

**Pull request merged**
