### PR TITLE
Restructure the tests into a folder + add tests

### PR DESCRIPTION
**Pull request by stellasphere**
# Description
Shifting to a folder structure for the tests to be housed in. The motivation was two-fold, to organize the main `web.py` file which was growing in length and complexity with every test added, as well as the added benefit of making the website dynamic in terms of adding a visual front-end for each of the tests. 

Also added:
- Annotation mistake identification test (annotation QA)
- Color recognition test

## Type of change
-   [x] New feature (breaking change)

## How has this change been tested, please provide a testcase or example of how you tested the change?
Tested locally, generating the `results/2023-11-26.json`, `results/2023-11-27.json` and `results/2023-11-28.json` successfully

## Any specific deployment considerations
Significant deployment considerations in terms of how future tests are added.

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by capjamesg** [comment]
This is a big improvement over how our tests are organized right now. Good job!

**Review by capjamesg — CHANGES_REQUESTED** [review]
This looks good. I noticed that some tests are being really verbose in the output, which limits our ability to programmatically evaluate them. Examples are the chart reading and RGB tests:

Screenshot 2023-11-28 at 09 47 51


Screenshot 2023-11-28 at 09 47 43

Perhaps we should tune the prompts before we release these?

**Comment by stellasphere** [comment]
I can try modifying the prompts, but I don't understand what you mean when you say it limits our ability to programmatically evaluate them. I extract JSON components using a markdown code block regex so they're still evaluated properly.

**Review by capjamesg — APPROVED** [review]
I didn't notice that we extracted JSON from the GPT output, so my prior comment is no longer relevant. This PR is good to go!

**Pull request merged**
